# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(613, 194)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(217, 217, 217);")
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Triangular)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.userLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.userLabel.setGeometry(QtCore.QRect(262, 43, 81, 16))
        self.userLabel.setObjectName("userLabel")
        self.userInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.userInput.setGeometry(QtCore.QRect(355, 35, 235, 31))
        self.userInput.setAutoFillBackground(False)
        self.userInput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.userInput.setClearButtonEnabled(False)
        self.userInput.setObjectName("userInput")
        self.pwLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.pwLabel.setGeometry(QtCore.QRect(260, 90, 81, 16))
        self.pwLabel.setObjectName("pwLabel")
        self.loginButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.loginButton.setGeometry(QtCore.QRect(500, 136, 69, 34))
        self.loginButton.setStyleSheet("background-color: rgb(165, 165, 165);\n"
"selection-background-color: rgb(165, 165, 165);")
        self.loginButton.setObjectName("loginButton")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(28, 26, 211, 142))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("resources/jae-logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.userInput_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.userInput_2.setGeometry(QtCore.QRect(355, 80, 235, 31))
        self.userInput_2.setAutoFillBackground(False)
        self.userInput_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.userInput_2.setClearButtonEnabled(False)
        self.userInput_2.setObjectName("userInput_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.userLabel.setText(_translate("MainWindow", "USERNAME:"))
        self.pwLabel.setText(_translate("MainWindow", "PASSWORD:"))
        self.loginButton.setText(_translate("MainWindow", "LOG IN"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())